package vcmsa.lubombuyu.imad_assignment2

import android.content.Intent
import android.content.pm.ActivityInfo
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.ImageButton
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity

class FlashcardActivity : AppCompatActivity() {


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
        setContentView(R.layout.activity_flashcard)

        // Code starts here
        // Declare all variables
        val edtQuestions = findViewById<EditText>(R.id.edtQuestions)
        val btnTrue = findViewById<Button>(R.id.btnTrue)
        val btnFalse = findViewById<Button>(R.id.btnFalse)
        val btnNext = findViewById<ImageButton>(R.id.btnINext)

        // Create the flashcard questions and answers
        // Questions where generated by ChatGPT, Prompt: Please give me 5 true or false questions about Africa.
        val questions = arrayListOf(
            "The Great Zimbabwe ruins were built by the Shona people.",
            "Ethiopia was never colonized by a European power.",
            "The Atlantic slave trade ended in the 20th century.",
            "Nelson Mandela was imprisoned for 27 years.",
            "Mansa Musa was a ruler of the Mali Empire."
        )

        // Answers to the questions
        val answers = arrayListOf(
            true,   // Shona people
            true,   // Ethiopia not colonized
            false,  // Slave trade ended in 19th century
            true,   // Mandela: 27 years
            true    // Mansa Musa ruled Mali
        )

        // Create tracking lists for quiz state
        val usedQuestions = arrayListOf<String>()
        val usedAnswers = arrayListOf<Boolean>()
        val userAnswers = arrayListOf<Boolean>()

        // Start with the first question
        var currentQuestion = questions.removeAt(0)
        var currentAnswer = answers.removeAt(0)
        edtQuestions.setText(currentQuestion)

        // Set buttons state
        // This is to reset the buttons to their original state
        btnNext.isEnabled = false
        btnTrue.isEnabled = true
        btnFalse.isEnabled = true

        // Checks for user input
        // If user clicks "True"
        btnTrue.setOnClickListener {
            userAnswers.add(true)
            usedQuestions.add(currentQuestion)
            usedAnswers.add(currentAnswer)

            // Show Toast if answer is correct or incorrect
            if (true == currentAnswer) {
                Toast.makeText(this, "Correct!", Toast.LENGTH_LONG).show()
            } else {
                Toast.makeText(this, "Incorrect! Correct answer is False.", Toast.LENGTH_LONG)
                    .show()
            }

            // Reset the buttons to their original state
            btnTrue.isEnabled = false
            btnFalse.isEnabled = false
            btnNext.isEnabled = true
        }

        // Checks for user input
        // If user clicks "False"
        btnFalse.setOnClickListener {
            userAnswers.add(false)
            usedQuestions.add(currentQuestion)
            usedAnswers.add(currentAnswer)

            // Show Toast if answer is correct or incorrect
            if (false == currentAnswer) {
                Toast.makeText(this, "Correct!", Toast.LENGTH_LONG).show()
            } else {
                Toast.makeText(this, "Incorrect! Correct answer is True.", Toast.LENGTH_LONG).show()
            }

            // Reset the buttons to their original state
            btnTrue.isEnabled = false
            btnFalse.isEnabled = false
            btnNext.isEnabled = true
        }

        // If user clicks "Next"
        // This will load the next question
        btnNext.setOnClickListener {
            // Check if there are more questions
            if (questions.isNotEmpty()) {
                // Load next question directly

                currentQuestion = questions.removeAt(0)
                currentAnswer = answers.removeAt(0)

                edtQuestions.setText(currentQuestion)
                btnTrue.isEnabled = true
                btnFalse.isEnabled = true
                btnNext.isEnabled = false
            } else {
                // Quiz finished: calculate score
                // Calculate score by comparing user's answers with correct answers
                var score = 0
                for (i in usedAnswers.indices) {
                    if (userAnswers[i] == usedAnswers[i]) {
                        score++
                    }
                }

                // Open ScoreActivity and send results
                val intent = Intent(this, ScoreActivity::class.java)
                intent.putExtra("correct", score)
                intent.putExtra("total", usedAnswers.size)
                intent.putStringArrayListExtra("questions", usedQuestions)
                intent.putExtra("correctAnswers", usedAnswers.toBooleanArray())
                intent.putExtra("userAnswers", userAnswers.toBooleanArray())
                startActivity(intent)
                finish()

            }
        }
    }
}

